solve.exe: simulated_annealing.cpp
	g++ -std=c++17 -O2 -o solve.exe simulated_annealing.cpp

solve_hebrew.exe: simulated_annealing_hebrew.cpp
	g++ -std=c++17 -O2 -o solve_hebrew.exe simulated_annealing_hebrew.cpp

clean:
	rm -f solve.exe
	rm -f solve_hebrew.exe

.PHONY: clean
