[project]
name = "shin-kamagaya"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "dash-cytoscape>=1.0.2",
    "ipykernel>=6.30.1",
    "nbformat>=5.10.4",
    "networkx>=3.5",
    "pandas>=2.3.2",
    "plotly[express]>=6.3.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
